// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzLNhWzpYYnzZJHZrcATxAPOsDu4I3vuQ',
    appId: '1:806704872233:web:5b697e21fdf8f1c65d1538',
    messagingSenderId: '806704872233',
    projectId: 'yourname-1325c',
    authDomain: 'yourname-1325c.firebaseapp.com',
    databaseURL: 'https://yourname-1325c-default-rtdb.firebaseio.com',
    storageBucket: 'yourname-1325c.firebasestorage.app',
    measurementId: 'G-94D8LNKGQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoJzN69H7hd8KaFBu76YvEZRKiQkswaB0',
    appId: '1:806704872233:android:6e23db19a1777c135d1538',
    messagingSenderId: '806704872233',
    projectId: 'yourname-1325c',
    databaseURL: 'https://yourname-1325c-default-rtdb.firebaseio.com',
    storageBucket: 'yourname-1325c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAsnK-f9qqWcFt76KJ-uq0WKs6l9Jr25o',
    appId: '1:806704872233:ios:16b1eff1c9bfef385d1538',
    messagingSenderId: '806704872233',
    projectId: 'yourname-1325c',
    databaseURL: 'https://yourname-1325c-default-rtdb.firebaseio.com',
    storageBucket: 'yourname-1325c.firebasestorage.app',
    iosClientId: '806704872233-bsksudlprahacm0784jfe5r0d2m88st0.apps.googleusercontent.com',
    iosBundleId: 'com.example.lafia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAsnK-f9qqWcFt76KJ-uq0WKs6l9Jr25o',
    appId: '1:806704872233:ios:16b1eff1c9bfef385d1538',
    messagingSenderId: '806704872233',
    projectId: 'yourname-1325c',
    databaseURL: 'https://yourname-1325c-default-rtdb.firebaseio.com',
    storageBucket: 'yourname-1325c.firebasestorage.app',
    iosClientId: '806704872233-bsksudlprahacm0784jfe5r0d2m88st0.apps.googleusercontent.com',
    iosBundleId: 'com.example.lafia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzLNhWzpYYnzZJHZrcATxAPOsDu4I3vuQ',
    appId: '1:806704872233:web:41f52ea5e6a19e825d1538',
    messagingSenderId: '806704872233',
    projectId: 'yourname-1325c',
    authDomain: 'yourname-1325c.firebaseapp.com',
    databaseURL: 'https://yourname-1325c-default-rtdb.firebaseio.com',
    storageBucket: 'yourname-1325c.firebasestorage.app',
    measurementId: 'G-FNTHMT92X9',
  );
}
